In [ ]:
# Basic array creation

import numpy as np
n = np.linspace(0, 1, 10, endpoint=True)[1:-1]   
print(n)

In [6]:
n = np.random.randint(0,100, size=20, dtype=int)
print(n)

[93 15 36 68 13  3 74 17 21 32 81  7  5 46 93 62 24 56 14 91]


In [8]:
n = np.repeat(7,16).reshape(4,4)
print(n)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [9]:
n = np.repeat(3.14, 10)
print(n)

[3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]


In [12]:
n = np.arange(1,10).reshape(3,3)
print(n)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
# Array Operations

a = np.array([1,3,5,7,9])
b = np.array([2,4,6,8,10])
sum_array = np.add(a, b)
print("SUM:", sum_array)


SUM: [ 3  7 11 15 19]


In [16]:
a = np.array([2,4,6,8])
product_array = np.multiply(a, 3)
print("PRODUCT:", product_array)

PRODUCT: [ 6 12 18 24]


In [17]:
a = np.array([10,20,30,40])
division_array = np.divide(a,2)
print("DIVISION:",division_array)

DIVISION: [ 5. 10. 15. 20.]


In [19]:
a = np.array([5,10,15])
b = np.array([2,3,4])
mod_array = np.remainder(a,b)
print("MOD:",mod_array)

MOD: [1 1 3]


In [20]:
a = np.array([1,2,3])
b = np.array([4,5,6])
dot_product = np.dot(a,b)
print("DOT:", dot_product)

DOT: 32


In [21]:
# Matrix Multiplication
a = ([2,3],[4,5])
b = ([1,0],[0,1])
mat_pro = np.dot(a,b)
print("PRO:", mat_pro)


PRO: [[2 3]
 [4 5]]


In [23]:
m =  np.arange(1,10).reshape(3,3)
v = np.array([1,0,1]).reshape(3,1)
output = np.dot(m,v)
print("O/P:",output)

O/P: [[ 4]
 [10]
 [16]]


In [26]:
i = np.identity(4)
r = np.random.randint(0,100, size=16, dtype=int).reshape(4,4)
output = np.dot(i,r)
print("O/P:",output)

O/P: [[43. 97. 73. 46.]
 [22. 41. 46. 57.]
 [54. 22. 75. 64.]
 [63. 10. 25. 96.]]


In [27]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
output = np.dot(a,b)
print("O/P:",output)

O/P: [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [29]:
a = np.arange(0,6).reshape(2,3)
b = np.arange(4,10).reshape(3,2)
output = np.dot(a,b)
print("O/P:",output)

O/P: [[22 25]
 [76 88]]


In [30]:
# Broadcasting
a = np.array([10, 20, 30])
scalar = 5
broad_array = a - scalar
print("Broadcast:",broad_array )

Broadcast: [ 5 15 25]


In [31]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
scalar = np.array([[1],[2],[3]])
broad_array = a + scalar
print("Broadcast:",broad_array )

Broadcast: [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [32]:
a = np.random.randint(0,100, size=16, dtype=int).reshape(4,4)
scalar  = 2
broad_array = a / scalar
print("Broadcast:",broad_array )

Broadcast: [[46.5 30.5 42.5  0.5]
 [38.  22.5  1.  40.5]
 [45.  12.5 27.  29.5]
 [36.  33.5 30.5 10. ]]


In [34]:
a = np.random.randint(0,100, size=9, dtype=int).reshape(3,3)
scalar  = 3
broad_array = a + scalar
print("Broadcast:",broad_array )

Broadcast: [[89 63 11]
 [52 52 11]
 [80 73 89]]


In [35]:
a = np.array([1,2,3,4,5])
scalar = np.random.randint(0,100, size=25, dtype=int).reshape(5,5)
broad_array = a * scalar
print("Broadcast:",broad_array )

Broadcast: [[  6  16 183 372 340]
 [ 47 184 267 296  15]
 [ 96 146  66 316 115]
 [ 90  54  75  76 265]
 [ 46 182  63 188 230]]


In [4]:
# Statistical Operations
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
med = np.median(a)
print("MED:", med)

MED: 5.5


In [10]:
from scipy import stats
a = np.array([1, 2, 2, 3, 4, 4, 4, 5, 6])
mode_array = stats.mode(a)
print("MODE:", mode_array)

MODE: ModeResult(mode=array([4]), count=array([3]))


In [11]:
a = np.array([10, 20, 30, 40, 50])
range_array = np.ptp(a)
print("RANGE:",range_array )

RANGE: 40


In [13]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
percentile_array = np.percentile(a,25)
print("PERCENTILE:",percentile_array )

PERCENTILE: 3.25


In [14]:
import numpy as np
x = np.array([1, 2, 3, 4, 5])
y = np.array([2,4, 6, 8, 10])
corr_coef = np.corrcoef(x,y)
print("CORR_COEF:",corr_coef)

CORR_COEF: [[1. 1.]
 [1. 1.]]


In [16]:
# Reshaping Arrays

a = np.array([1,2,3,4,5,6,7,8,9,10,11,12]).reshape(3,4)
print(a)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [20]:
a = np.random.randint(0,100, size=12, dtype=int).reshape(6,2)
print(a)
print("\n")
b = a.reshape(3,4)
print(b)

[[44 81]
 [21 93]
 [78 79]
 [95 84]
 [20 98]
 [48 61]]


[[44 81 21 93]
 [78 79 95 84]
 [20 98 48 61]]


In [21]:
a = np.random.randint(0,100, size=16, dtype=int).reshape(4,4)
print(a)
print("\n")
b = a.flatten()
print(b)

[[46  4  3 20]
 [13 12 41 91]
 [57 55 49 42]
 [79 88 61 71]]


[46  4  3 20 13 12 41 91 57 55 49 42 79 88 61 71]


In [22]:
a = np.random.randint(0,100, size=24, dtype=int).reshape(2,3,4)
print(a)
print("\n")
b = a.reshape(4,3,2)
print(b)

[[[36 71  6 18]
  [15 99 71 96]
  [63 90 53 95]]

 [[49 57 90 43]
  [23  2 37 27]
  [36 35 85 63]]]


[[[36 71]
  [ 6 18]
  [15 99]]

 [[71 96]
  [63 90]
  [53 95]]

 [[49 57]
  [90 43]
  [23  2]]

 [[37 27]
  [36 35]
  [85 63]]]


In [23]:
a = np.array([1,2,3,4])
b =  a.reshape(1,4)
print(b)

[[1 2 3 4]]


In [24]:
# Element-wise Operations
a = np.array([1,3,5])
b = np.array([2,4,6])
div_arr = a / b
print("DIV:", div_arr)

DIV: [0.5        0.75       0.83333333]


In [30]:
a = np.array([2, 4, 6])
b = np.array([1, 3, 5])
mod_arr = np.remainder(a,b)
print("mod:", mod_arr)

mod: [0 1 1]


In [31]:
a = np.array([1, 2, 3, 4, 5])
scalar = 10
add_arr = a + 10
print(add_arr)

[11 12 13 14 15]


In [32]:
a = np.array([10, 20, 30, 40, 50])
scalar = 5
sub_arr = a -5
print(sub_arr)

[ 5 15 25 35 45]


In [35]:
a = np.array([1, 2, 3, 4, 5])
squa_arr = np.square(a)
print(squa_arr)

[ 1  4  9 16 25]


In [37]:
# Slicing and Indexing
a = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
element = a[1,1,1]
print(a)
print(element)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
11


In [38]:
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], 
                     [[7, 8, 9], [10, 11, 12]]])

first_layer = array_3d[0]
print("First layer:")
print(first_layer)

First layer:
[[1 2 3]
 [4 5 6]]


In [39]:

array_2d = np.array([[10, 20, 30], 
                     [40, 50, 60], 
                     [70, 80, 90]])
last_row = array_2d[-1]
print("Last row:")
print(last_row)

Last row:
[70 80 90]


In [40]:
array_2d = np.array([[10, 20, 30], 
                     [40, 50, 60], 
                     [70, 80, 90]])
first_column = array_2d[:, 0]
print("First column:")
print(first_column)


First column:
[10 40 70]


In [41]:

array_2d = np.array([[10, 20, 30], 
                     [40, 50, 60], 
                     [70, 80, 90]])
sliced_array = array_2d[-2:, -2:]
print("Sliced array:")
print(sliced_array)


Sliced array:
[[50 60]
 [80 90]]


In [48]:
# Creating Random Arrays
random_array = np.random.rand(20)
print("Random array:")
print(random_array)


Random array:
[0.85539877 0.83893658 0.03731509 0.04356148 0.03256618 0.87597056
 0.75103    0.16024862 0.21439569 0.74909319 0.47614947 0.54854128
 0.99618679 0.9254123  0.11540276 0.37116289 0.29439623 0.441144
 0.92497372 0.13360865]


In [49]:
random_array = np.random.randint(10, 21, size=(4, 4))
print("4x4 array:")
print(random_array)


4x4 array:
[[14 15 13 19]
 [20 13 15 19]
 [13 14 19 15]
 [13 14 13 20]]


In [50]:
random_array = np.random.uniform(-1, 1, size=(3, 3))
print("3x3 array:")
print(random_array)


3x3 array:
[[ 0.37638648  0.22943997  0.77470063]
 [ 0.13847811 -0.11176025  0.01759227]
 [ 0.4010829   0.70465774  0.67107276]]


In [51]:
random_array = np.random.randint(100, 201, size=15)
print("Array with 15 random values:")
print(random_array)


Array with 15 random values:
[196 200 120 149 155 105 132 194 103 131 188 183 116 160 188]


In [52]:
random_array = np.random.uniform(0, 10, size=(5, 5))

print("5x5 array:")
print(random_array)


5x5 array:
[[1.69955378 7.19380678 9.90945128 0.86271757 9.81830894]
 [0.73191456 8.01827277 2.81643313 6.20856559 9.72938611]
 [0.23519406 9.86655305 8.15551459 4.49945323 1.18308752]
 [5.60046001 3.93003038 4.74397434 1.47902302 9.21089946]
 [6.81648511 8.81758683 2.25917386 5.30671001 3.52391139]]


In [53]:
# Stacking and Concatenating Arrays

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
stacked_array = np.vstack((a, b))
print("Vertically stacked array:")
print(stacked_array)


Vertically stacked array:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [54]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
result = np.hstack((a, b))
print(result)


[[1 2 5 6]
 [3 4 7 8]]


In [55]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.concatenate((a, b))
print(result)


[1 2 3 4 5 6]


In [56]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
result = np.vstack((a, b))
print(result)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [57]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
result = np.hstack((a, b))
print(result)


[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]
