In [ ]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense


In [ ]:
data=load_iris()

In [ ]:
x=data.data
y=data.target

In [ ]:
y.size

150

In [ ]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder

In [ ]:
scaler=StandardScaler()
x_scaled=scaler.fit_transform(x)


In [ ]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
x_scaled

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

In [ ]:
from keras.utils import to_categorical

In [ ]:
y_encoded=to_categorical(y)

In [ ]:
y_encoded

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x_scaled,y_encoded,test_size=0.2)

In [ ]:
x_train.shape

(120, 4)

In [ ]:
model=Sequential()
model.add(Dense(32,input_shape=(x_train.shape[1],),activation='relu'))
model.add(Dense(3,activation='softmax'))


In [ ]:
model.compile(optimizer='Adam',loss='categorical_crossentropy',metrics='accuracy')

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 32)                160       
                                                                 
 dense_2 (Dense)             (None, 3)                 99        
                                                                 
Total params: 259 (1.01 KB)
Trainable params: 259 (1.01 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.fit(x_train,y_train,epochs=50)

Epoch 1/50
4/4 [==============================] - 0s 4ms/step - loss: 1.2458 - accuracy: 0.3250
Epoch 2/50
4/4 [==============================] - 0s 3ms/step - loss: 1.1953 - accuracy: 0.3083
Epoch 3/50
4/4 [==============================] - 0s 4ms/step - loss: 1.1489 - accuracy: 0.3333
Epoch 4/50
4/4 [==============================] - 0s 5ms/step - loss: 1.1038 - accuracy: 0.3417
Epoch 5/50
4/4 [==============================] - 0s 4ms/step - loss: 1.0585 - accuracy: 0.3833
Epoch 6/50
4/4 [==============================] - 0s 4ms/step - loss: 1.0174 - accuracy: 0.4250
Epoch 7/50
4/4 [==============================] - 0s 3ms/step - loss: 0.9774 - accuracy: 0.4833
Epoch 8/50
4/4 [==============================] - 0s 4ms/step - loss: 0.9401 - accuracy: 0.5417
Epoch 9/50
4/4 [==============================] - 0s 3ms/step - loss: 0.9037 - accuracy: 0.6000
Epoch 10/50
4/4 [==============================] - 0s 3ms/step - loss: 0.8718 - accuracy: 0.6250
Epoch 11/50
4/4 [======================

In [ ]:
loss,accuracy=model.evaluate(x_test,y_test)

1/1 [==============================] - 0s 25ms/step - loss: 0.3444 - accuracy: 0.8667


In [ ]:
print('loss: ',loss)
print('accuracy',accuracy)

loss:  0.3444008231163025
accuracy 0.8666666746139526


#Pytorch version

In [ ]:
# Import necessary libraries
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from torch.utils.data import DataLoader, TensorDataset

# Load the Iris dataset
data = load_iris()
x = data.data
y = data.target

# Standardize the input features
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)

# One-hot encode the labels
encoder = OneHotEncoder(sparse=False)
y_encoded = encoder.fit_transform(y.reshape(-1, 1))

# Split the dataset into training and test sets
x_train, x_test, y_train, y_test = train_test_split(x_scaled, y_encoded, test_size=0.2, random_state=42)

# Convert data to PyTorch tensors
x_train_tensor = torch.tensor(x_train, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.float32)
x_test_tensor = torch.tensor(x_test, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32)

# Create DataLoader for batch processing
train_dataset = TensorDataset(x_train_tensor, y_train_tensor)
train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)

# Define the MLP model in PyTorch
class MLP(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(MLP, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(hidden_size, output_size)
        self.softmax = nn.Softmax(dim=1)

    def forward(self, x):
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        x = self.softmax(x)
        return x

# Initialize the model, loss function, and optimizer
input_size = x_train.shape[1]
hidden_size = 32
output_size = y_train.shape[1]
model = MLP(input_size, hidden_size, output_size)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Training loop
epochs = 50
for epoch in range(epochs):
    for inputs, labels in train_loader:
        # Forward pass
        outputs = model(inputs)
        loss = criterion(outputs, labels)

        # Backward pass and optimization
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    # Print the loss for every epoch
    print(f'Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}')

# Evaluate the model on the test set
model.eval()  # Set the model to evaluation mode
with torch.no_grad():
    test_outputs = model(x_test_tensor)
    test_loss = criterion(test_outputs, y_test_tensor).item()
    _, predicted = torch.max(test_outputs, 1)
    _, actual = torch.max(y_test_tensor, 1)
    accuracy = (predicted == actual).float().mean().item()

print(f'Loss: {test_loss:.4f}')
print(f'Accuracy: {accuracy * 100:.2f}%')


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


Epoch [1/50], Loss: 1.1171
Epoch [2/50], Loss: 1.0669
Epoch [3/50], Loss: 1.1030
Epoch [4/50], Loss: 1.0305
Epoch [5/50], Loss: 1.0309
Epoch [6/50], Loss: 1.0205
Epoch [7/50], Loss: 0.9553
Epoch [8/50], Loss: 0.9962
Epoch [9/50], Loss: 0.9977
Epoch [10/50], Loss: 0.9751
Epoch [11/50], Loss: 0.8566
Epoch [12/50], Loss: 0.8806
Epoch [13/50], Loss: 0.9383
Epoch [14/50], Loss: 0.9058
Epoch [15/50], Loss: 0.8060
Epoch [16/50], Loss: 0.8962
Epoch [17/50], Loss: 0.8138
Epoch [18/50], Loss: 0.6730
Epoch [19/50], Loss: 0.7647
Epoch [20/50], Loss: 0.8862
Epoch [21/50], Loss: 0.8335
Epoch [22/50], Loss: 0.8726
Epoch [23/50], Loss: 0.7902
Epoch [24/50], Loss: 0.7767
Epoch [25/50], Loss: 0.8464
Epoch [26/50], Loss: 0.8077
Epoch [27/50], Loss: 0.7238
Epoch [28/50], Loss: 0.6777
Epoch [29/50], Loss: 0.8620
Epoch [30/50], Loss: 0.7768
Epoch [31/50], Loss: 0.7595
Epoch [32/50], Loss: 0.7406
Epoch [33/50], Loss: 0.6992
Epoch [34/50], Loss: 0.8158
Epoch [35/50], Loss: 0.8133
Epoch [36/50], Loss: 0.7982
E